CREATE TABLE IF NOT EXISTS "SQLBootcamp_Assignment_6" (
    "SQLBootcamp_Assignment_6" TEXT,
    "Column_2" TEXT,
    "Column_3" TEXT,
    "Column_4" TEXT
);
INSERT INTO "SQLBootcamp_Assignment_6" VALUES (NULL,NULL,NULL,NULL),
	('1.SELECT product_name',' ',NULL,NULL),
	('       units_in_stock',' ',NULL,NULL),
	('       CASE ',NULL,NULL,NULL),
	('           WHEN units_in_stock = 0 THEN ''Out of Stock''',NULL,NULL,NULL),
	('           WHEN units_in_stock < 20 THEN ''Low Stock''',NULL,NULL,NULL),
	('           ELSE ''In Stock''',NULL,NULL,NULL),
	('       END AS stock_status',NULL,NULL,NULL),
	('FROM products;',NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL),
	('2.SELECT product_name',' unit_price',NULL,NULL),
	('FROM products',NULL,NULL,NULL),
	('WHERE category_id = (',NULL,NULL,NULL),
	('    SELECT category_id',NULL,NULL,NULL),
	('    FROM categories',NULL,NULL,NULL),
	('    WHERE category_name = ''Drinks''',NULL,NULL,NULL),
	(');',NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL),
	('3.SELECT order_id',' order_date',' freight',' employee_id'),
	('FROM orders',NULL,NULL,NULL),
	('WHERE employee_id = (',NULL,NULL,NULL),
	('    SELECT employee_id',NULL,NULL,NULL),
	('    FROM orders',NULL,NULL,NULL),
	('    GROUP BY employee_id',NULL,NULL,NULL),
	('    ORDER BY COUNT(order_id) DESC',NULL,NULL,NULL),
	('    LIMIT 1',NULL,NULL,NULL),
	(');',NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL),
	('4.SELECT order_id',' order_date',' freight',' ship_country'),
	('FROM orders',NULL,NULL,NULL),
	('WHERE ship_country != ''USA''',NULL,NULL,NULL),
	('AND freight > ANY (',NULL,NULL,NULL),
	('    SELECT freight',NULL,NULL,NULL),
	('    FROM orders',NULL,NULL,NULL),
	('    WHERE ship_country = ''USA''',NULL,NULL,NULL),
	(');',NULL,NULL,NULL);
