CREATE TABLE IF NOT EXISTS "SQL_5" (
    "SQL_5" TEXT,
    "Column_2" TEXT,
    "Column_3" TEXT,
    "Column_4" TEXT,
    "Column_5" TEXT
);
INSERT INTO "SQL_5" VALUES (NULL,NULL,NULL,NULL,NULL),
	('1.GROUP BY with WHERE - Orders by Year and Quarter',NULL,NULL,NULL,NULL),
	('Display',' order year',' quarter',' order count',' avg freight cost only for those orders where freight cost > 100'),
	(NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL),
	('SELECT ',NULL,NULL,NULL,NULL),
	('    YEAR(order_date) AS order_year',NULL,NULL,NULL,NULL),
	('    QUARTER(order_date) AS order_quarter',NULL,NULL,NULL,NULL),
	('    COUNT(order_id) AS order_count',NULL,NULL,NULL,NULL),
	('    AVG(freight) AS avg_freight_cost',NULL,NULL,NULL,NULL),
	('FROM ',NULL,NULL,NULL,NULL),
	('    orders',NULL,NULL,NULL,NULL),
	('WHERE ',NULL,NULL,NULL,NULL),
	('    freight > 100',NULL,NULL,NULL,NULL),
	('GROUP BY ',NULL,NULL,NULL,NULL),
	('    YEAR(order_date)',' QUARTER(order_date);',NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL),
	('2.GROUP BY with HAVING - High Volume Ship Regions',NULL,NULL,NULL,NULL),
	('Display',' ship region',' no of orders in each region',' min and max freight cost',NULL),
	(' Filter regions where no of orders >= 5',NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL),
	('SELECT ',NULL,NULL,NULL,NULL),
	('    ship_region',NULL,NULL,NULL,NULL),
	('    COUNT(order_id) AS no_of_orders',NULL,NULL,NULL,NULL),
	('    MIN(freight) AS min_freight_cost',NULL,NULL,NULL,NULL),
	('    MAX(freight) AS max_freight_cost',NULL,NULL,NULL,NULL),
	('FROM ',NULL,NULL,NULL,NULL),
	('    orders',NULL,NULL,NULL,NULL),
	('GROUP BY ',NULL,NULL,NULL,NULL),
	('    ship_region',NULL,NULL,NULL,NULL),
	('HAVING ',NULL,NULL,NULL,NULL),
	('    COUNT(order_id) >= 5;',NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL),
	('3.Get all title designations across employees and customers ( Try UNION & UNION ALL)',NULL,NULL,NULL,NULL),
	('SELECT title AS designation FROM employees',NULL,NULL,NULL,NULL),
	('UNION',NULL,NULL,NULL,NULL),
	('SELECT contact_title AS designation FROM customers;',NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL),
	('SELECT title AS designation FROM employees',NULL,NULL,NULL,NULL),
	('UNION All',NULL,NULL,NULL,NULL),
	('SELECT contact_title AS designation FROM customers;',NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL),
	('4.Find categories that have both discontinued and in-stock products',NULL,NULL,NULL,NULL),
	('(Display category_id',' instock means units_in_stock > 0',' Intersect)',NULL,NULL),
	('SELECT category_id',NULL,NULL,NULL,NULL),
	('FROM products',NULL,NULL,NULL,NULL),
	('WHERE discontinued = 1',NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL),
	('INTERSECT',NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL),
	('SELECT category_id',NULL,NULL,NULL,NULL),
	('FROM products',NULL,NULL,NULL,NULL),
	('WHERE units_in_stock > 0;',NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL),
	('5. Find orders that have no discounted items (Display the  order_id',' EXCEPT)',NULL,NULL,NULL),
	('SELECT order_id ',NULL,NULL,NULL,NULL),
	('FROM order_details',NULL,NULL,NULL,NULL),
	('EXCEPT',NULL,NULL,NULL,NULL),
	('SELECT order_id ',NULL,NULL,NULL,NULL),
	('FROM order_details',NULL,NULL,NULL,NULL),
	('WHERE discount > 0;',NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL);
