CREATE TABLE IF NOT EXISTS "Bhuvana_SQL_Assignment_10" (
    "function_to_Calculate_the_total_stock_value_for_a_given_category" TEXT,
    "Column_2" TEXT,
    "Column_3" TEXT,
    "Column_4" TEXT
);
INSERT INTO "Bhuvana_SQL_Assignment_10" VALUES ('(Stock value=ROUND(SUM(unit_price * units_in_stock)::DECIMAL',' 2)',NULL,NULL),
	('Return data type is DECIMAL(10','2)',NULL,NULL),
	(NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL),
	('CREATE FUNCTION calculate_stock_value(category_id_param INT) ',NULL,NULL,NULL),
	('RETURNS DECIMAL(10','2) AS ',NULL,NULL),
	('$$',NULL,NULL,NULL),
	('DECLARE stock_value DECIMAL(10','2);',NULL,NULL),
	('BEGIN',NULL,NULL,NULL),
	('    SELECT ROUND(SUM(unit_price * units_in_stock)::DECIMAL',' 2) ',NULL,NULL),
	('    INTO stock_value',NULL,NULL,NULL),
	('    FROM products',NULL,NULL,NULL),
	('    WHERE category_id = category_id_param;',NULL,NULL,NULL),
	('    ',NULL,NULL,NULL),
	('    RETURN stock_value;',NULL,NULL,NULL),
	('END;',NULL,NULL,NULL),
	('$$ LANGUAGE plpgsql;',NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL),
	('SELECT calculate_stock_value(1);',NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL),
	('2.Cursor Query:',NULL,NULL,NULL),
	('create or replace procedure update_prices_with_cursor()',NULL,NULL,NULL),
	('language plpgsql',NULL,NULL,NULL),
	('as $$',NULL,NULL,NULL),
	('declare',NULL,NULL,NULL),
	('product_cursor cursor for ',NULL,NULL,NULL),
	('select product_id','product_name','unit_price','units_in_stock from products where discontinued=0;'),
	(NULL,NULL,NULL,NULL),
	('product_record record;',NULL,NULL,NULL),
	('v_new_price decimal(10','2);',NULL,NULL),
	('Begin',NULL,NULL,NULL),
	('open product_cursor;',NULL,NULL,NULL),
	('loop',NULL,NULL,NULL),
	('fetch product_cursor into product_record;',NULL,NULL,NULL),
	('exit when not found;',NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL),
	('---new price calculation',NULL,NULL,NULL),
	('if product_record.units_in_stock < 10 THEN',NULL,NULL,NULL),
	('            v_new_price:=product_record.unit_price * 1.1;',NULL,NULL,NULL),
	('			else',NULL,NULL,NULL),
	('			 v_new_price:=product_record.unit_price * 0.95;			',NULL,NULL,NULL),
	('end if;',NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL),
	('			UPDATE products',NULL,NULL,NULL),
	('            SET unit_price=Round(v_new_price','2)',NULL,NULL),
	('            WHERE product_id = product_record.product_id;',NULL,NULL,NULL),
	('			',NULL,NULL,NULL),
	('raise notice ''Updated price % from % to %''',NULL,NULL,NULL),
	('product_record.product_name',NULL,NULL,NULL),
	('product_record.unit_price',NULL,NULL,NULL),
	('v_new_price;',NULL,NULL,NULL),
	('end loop;',NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL),
	('close product_cursor;',NULL,NULL,NULL),
	('end ;',NULL,NULL,NULL),
	('$$;',NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL),
	('Call update_prices_with_cursor();',NULL,NULL,NULL),
	(' ',NULL,NULL,NULL);
