CREATE TABLE IF NOT EXISTS "Bhuvana_SQL_Bootcamp_Assignment_8" (
    "SQL_Bootcamp_Assignment_8" TEXT,
    "Column_2" TEXT,
    "Column_3" TEXT,
    "Column_4" TEXT
);
INSERT INTO "Bhuvana_SQL_Bootcamp_Assignment_8" VALUES (NULL,NULL,NULL,NULL),
	('1.CREATE VIEW vw_updatable_products AS',NULL,NULL,NULL),
	('SELECT product_id',' product_name',' unit_price',' units_in_stock'),
	('FROM products',NULL,NULL,NULL),
	('WHERE units_in_stock < 10;',NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL),
	('UPDATE products',NULL,NULL,NULL),
	('SET unit_price = unit_price * 1.1',NULL,NULL,NULL),
	('WHERE units_in_stock < 10;',NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL),
	('2.BEGIN TRANSACTION;',NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL),
	('UPDATE products',NULL,NULL,NULL),
	('SET unit_price = unit_price * 1.1',NULL,NULL,NULL),
	('WHERE category_id = 1;',NULL,NULL,NULL),
	('-- Check the updated data before committing',NULL,NULL,NULL),
	('SELECT * FROM products WHERE category_id = 1;',NULL,NULL,NULL),
	('COMMIT;',NULL,NULL,NULL),
	('ROLLBACK;',NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL),
	('3.CREATE VIEW vw_employee_territories AS',NULL,NULL,NULL),
	('SELECT e.employee_id',' ',NULL,NULL),
	('       CONCAT(e.first_name',' '' ''',' e.last_name) AS employee_full_name',NULL),
	('       e.title',' ',NULL,NULL),
	('       t.territory_id',' ',NULL,NULL),
	('       t.territory_description',' ',NULL,NULL),
	('       r.region_description',NULL,NULL,NULL),
	('FROM employees e',NULL,NULL,NULL),
	('JOIN employee_territories et ON e.employee_id = et.employee_id',NULL,NULL,NULL),
	('JOIN territories t ON et.territory_id = t.territory_id',NULL,NULL,NULL),
	('JOIN region r ON t.region_id = r.region_id;',NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL),
	('select * from vw_employee_territories;',NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL),
	('4.with recursive cte_employees_hierarchy as',NULL,NULL,NULL),
	('( select employee_id',NULL,NULL,NULL),
	('first_name || '''' || last_name as employee_name',NULL,NULL,NULL),
	('reports_to',NULL,NULL,NULL),
	('1 as level',NULL,NULL,NULL),
	('from employees ',NULL,NULL,NULL),
	('where reports_to is NULL',NULL,NULL,NULL),
	(' ',NULL,NULL,NULL),
	(' UNION ALL',NULL,NULL,NULL),
	(' ',NULL,NULL,NULL),
	('select e.employee_id',NULL,NULL,NULL),
	('e.first_name || '''' || e.last_name as employee_name',NULL,NULL,NULL),
	('e.reports_to','eh.level +1 ',NULL,NULL),
	('from employees e',NULL,NULL,NULL),
	('INNER JOIN cte_employees_hierarchy eh ON e.reports_to = eh.employee_id',NULL,NULL,NULL),
	(')',NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL),
	('SELECT * FROM cte_employees_hierarchy',NULL,NULL,NULL),
	('ORDER BY level',' reports_to',' employee_id;',NULL);
