CREATE TABLE IF NOT EXISTS "Day4_Assignment_SQLBOOTCAMP" (
    "Day4_Assignment_SQLBOOTCAMP" TEXT,
    "Column_2" TEXT,
    "Column_3" TEXT,
    "Column_4" TEXT,
    "Column_5" TEXT
);
INSERT INTO "Day4_Assignment_SQLBOOTCAMP" VALUES (NULL,NULL,NULL,NULL,NULL),
	('--1',NULL,NULL,NULL,NULL),
	('select  c.company_name AS customer','o.order_id','p.product_name','p.quantity_per_unit','o.order_date'),
	('from customers c JOIN orders o ON c.customer_id=o.customer_id',NULL,NULL,NULL,NULL),
	('				  JOIN order_details od ON od.order_id=o.order_id',NULL,NULL,NULL,NULL),
	('				  JOIN products p ON p.product_id=od.product_id',NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL),
	('--2',NULL,NULL,NULL,NULL),
	('select o.order_id','e.first_name || '' '' || e.last_name AS employeeName','o.ship_name','p.product_name','c.company_name'),
	('from orders o LEFT JOIN customers c ON o.customer_id=c.customer_id',NULL,NULL,NULL,NULL),
	('			 LEFT JOIN employees e ON o.employee_id=e.employee_id',NULL,NULL,NULL,NULL),
	('			 LEFT JOIN order_details od ON od.order_id=o.order_id',NULL,NULL,NULL,NULL),
	('			 LEFT JOIN products p ON p.product_id=od.product_id',NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL),
	('--3',NULL,NULL,NULL,NULL),
	('select od.order_id','p.product_id','p.quantity_per_unit','p.product_name ',NULL),
	('from order_details od RIGHT JOIN products p ON p.product_id=od.product_id',NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL),
	('--4',NULL,NULL,NULL,NULL),
	('select p.product_id','c.category_name','p.product_name','c.category_id',NULL),
	('from products p FULL OUTER JOIN categories c ON c.category_id=p.category_id',NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL),
	('--5',NULL,NULL,NULL,NULL),
	('select p.product_id','c.category_name',NULL,NULL,NULL),
	('from products p CROSS JOIN categories c',NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL),
	('--6',NULL,NULL,NULL,NULL),
	('select e1.first_name || '' '' || e1.last_name AS employee_name',NULL,NULL,NULL,NULL),
	('e2.first_name || '' '' || e2.last_name AS manager_name',NULL,NULL,NULL,NULL),
	('from employees e1 JOIN employees e2 on e1.reports_to=e2.employee_id',NULL,NULL,NULL,NULL),
	('where e1.employee_id!=e2.employee_id',NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL),
	('--7',NULL,NULL,NULL,NULL),
	('select c.customer_id','c.contact_name','o.ship_via',NULL,NULL),
	('from customers c LEFT JOIN orders o ON c.customer_id=o.customer_id',NULL,NULL,NULL,NULL),
	('where o.ship_via IS NULL',NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL);
